# /
GET {{url}}:{{port}}

###

# REGISTER
POST {{url}}:{{port}}/register HTTP/1.1
content-type: application/json

{
  "name":"test",
  "email":"test@test.io",
  "password":"111111"
}

###

# LOGIN
POST {{url}}:{{port}}/login
Content-Type: application/json

{
  "email":"test@test.io",
  "password":"111111"
}

# {
#   "email":"admin@admin.io",
#   "password":"111111Qq"
# }

###

# TOKEN
POST {{url}}:{{port}}/token
Content-Type: application/json

{
    "refresh_token": "{{refresh_token}}"
}
